export const persian={
    code: 'per',
    toolbar: {
        default: 'پیش فرض',
        save: 'ذخیره',
        font: 'فونت',
        formats: 'فارمت',
        fontSize: 'اندازه',
        bold: 'بولد',
        underline: 'زیر خط',
        italic: 'کج',
        strike: 'منقضی شده',
        subscript: 'Subscript',
        superscript: 'Superscript',
        removeFormat: 'Remove Format',
        fontColor: 'رنگ فونت',
        hiliteColor: 'رنگ پس زمینه',
        indent: 'Indent',
        outdent: 'Outdent',
        align: 'موقعیت',
        alignLeft: 'موقعیت چپ',
        alignRight: 'موقعیت راست',
        alignCenter: 'موقعیت مرکز',
        alignJustify: 'موقعیت اصلاح شده',
        list: 'لیست',
        orderList: 'لیست ترتیبی',
        unorderList: 'لیست بدون ترتیب',
        horizontalRule: 'خط افقی',
        hr_solid: 'خشک',
        hr_dotted: 'نقطه ای',
        hr_dashed: 'خطی',
        table: 'جدول',
        link: 'Link',
        math: 'Math',
        image: 'Image',
        video: 'Video',
        audio: 'Audio',
        fullScreen: 'تمام صفحه',
        showBlocks: 'Show blocks',
        codeView: 'Code view',
        undo: 'برگشت',
        redo: 'انجام دوباره',
        preview: 'دیدن',
        print: 'چاپ',
        tag_p: 'پراگراف',
        tag_div: 'نورمال (DIV)',
        tag_h: 'سرخط',
        tag_blockquote: 'کوتیشن',
        tag_pre: 'کد',
        template: 'Template',
        lineHeight: 'Line height',
        paragraphStyle: 'ستایل پاراگراف',
        textStyle: 'Text style',
        imageGallery: 'Image gallery',
        mention: 'Mention'
    },
    dialogBox: {
        linkBox: {
            title: 'Insert Link',
            url: 'URL to link',
            text: 'Text to display',
            newWindowCheck: 'Open in new window',
            downloadLinkCheck: 'Download link',
            bookmark: 'Bookmark'
        },
        mathBox: {
            title: 'Math',
            inputLabel: 'Mathematical Notation',
            fontSizeLabel: 'Font Size',
            previewLabel: 'Preview'
        },
        imageBox: {
            title: 'Insert image',
            file: 'Select from files',
            url: 'Image URL',
            altText: 'Alternative text'
        },
        videoBox: {
            title: 'Insert Video',
            file: 'Select from files',
            url: 'Media embed URL, YouTube/Vimeo'
        },
        audioBox: {
            title: 'Insert Audio',
            file: 'Select from files',
            url: 'Audio URL'
        },
        browser: {
            tags: 'Tags',
            search: 'Search',
        },
        caption: 'Insert description',
        close: 'Close',
        submitButton: 'Submit',
        revertButton: 'Revert',
        proportion: 'Constrain proportions',
        basic: 'Basic',
        left: 'Left',
        right: 'Right',
        center: 'Center',
        width: 'Width',
        height: 'Height',
        size: 'Size',
        ratio: 'Ratio'
    },
    controller: {
        edit: 'ویرایش',
        unlink: 'بدون لینک',
        remove: 'حذف',
        insertRowAbove: 'سطر جدید در بالا',
        insertRowBelow: 'سطر جدید در زیر',
        deleteRow: 'حذف سطر',
        insertColumnBefore: 'سطون جدید قبل از',
        insertColumnAfter: 'سطون جدید بعد از',
        deleteColumn: 'حذف سطون',
        fixedColumnWidth: 'عرض سطون ثابت',
        resize100: 'Resize 100%',
        resize75: 'Resize 75%',
        resize50: 'Resize 50%',
        resize25: 'Resize 25%',
        autoSize: 'Auto size',
        mirrorHorizontal: 'Mirror, Horizontal',
        mirrorVertical: 'Mirror, Vertical',
        rotateLeft: 'Rotate left',
        rotateRight: 'Rotate right',
        maxSize: 'Max size',
        minSize: 'Min size',
        tableHeader: 'Table header',
        mergeCells: 'Merge cells',
        splitCells: 'Split Cells',
        HorizontalSplit: 'Horizontal split',
        VerticalSplit: 'Vertical split'
    },
    menu: {
        spaced: 'فاصله دار',
        bordered: 'سرحد دار',
        neon: 'هیچ کدام',
        translucent: 'Translucent',
        shadow: 'سایه ای',
        code: 'کد'
    }
}
